
common: &COMMON
  encoding: utf8
  pool: 5
  timeout: 5000

development:
  <<: *COMMON
  adapter: mysql2
  database: nabu_devel
  host: localhost
  user: root

production: &PRODUCTION
  <<: *COMMON
  adapter: mysql2
  host: localhost
  database: nabu
  user: root

staging:
  <<: *PRODUCTION

uat:
  <<: *PRODUCTION

test: &test
  <<: *COMMON
  adapter: sqlite3
  database: ":memory:"
  verbosity: quiet
