
common: &COMMON
  encoding: utf8
  pool: 5
  timeout: 5000

development:
  <<: *COMMON
  adapter: sqlite3
  database: db/development.sqlite3

production:
  <<: *COMMON
  adapter: mysql2
  host: localhost
  database: nabu

test: &test
  <<: *COMMON
  adapter: sqlite3
  database: ":memory:"
  verbosity: quiet

cucumber:
  <<: *test
